# Este workflow fará uma instalação limpa das dependências do Node, cache/restauração delas, build do código-fonte e execução dos testes em diferentes versões do Node
# Para mais informações, veja: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
